---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "http://catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    name: cart
    tier: cart-app
spec:
  containers:
  - name: cart
    imagePullPolicyL: Always
    image: kiranprav/cart:v1
    envFrom:
    - configMapRef:
        name: cart-config
    resources:
      requests:
        cpu: "100m"
        memory: "130Mi"
      limits:
        cpu: "150m"
        memory: "150Mi"
---
apiVersion:
kind: Service
metadata:
  name: cart
spec:
  selector:
    name: cart
    tier: cart-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080