---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  CATALOGUE_HOST: "http://catalogue"
  REDIS_HOST: "redis"

---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    name: cart
    tier: cart-app
spec:
  containers:
  - name: cart
    imagePullPolicy: Always
    image: kiranprav/cart:v2
    envFrom:
 
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    name: cart
    tier: cart-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080