---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: c2VjcmV0

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
labels:
  name: mysql
  tier: Database
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: kiranprav/mysql:v1
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretRef:
        name: mysql-secret
    ports:
      - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    name: mysql
    tier: Database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

