---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tire: database
spec:
  containers:
    - name: mongodb
      imagePullPolicy: Always
      image: kiranprav/mongo:v1
      ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    name: mongodb
    tire: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
