---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongodb
    tire: database
spec:
  containers:
    - name: mongodb
      imagePullPolicy: Always
      image: kiranprav/mongo:v1
      ports:
        - containerPort: 27017
---
apiversion: v1
kind: Service
metadata:
  name: MONGO
spec:
  selector:
    name: mongodb
    tire: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
