---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongodb
    tire: database
spec:
  containers:
    - name: mongodb
      imagePullPolicy: Always
      image: kiranprav/mongo:v1
      ports:
        - containerPort: 27017
      resources:
        requests:
          cpu: "100m"
          memory: "150Mi"
        limits:
          cpu: "135m"
          memory: "200Mi"
---
apiversion: v1
kind: Service
metadata:
  name: MONGDB-SERVICE
spec:
  selector:
    name: mongodb
    tire: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
