---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:80/user"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
    tier: used-for-login
spec:
  containers:
  - name: user
    imagePullPolicy: Always
    image: kiranprav/user:v1
    envFrom:
      ConfigMapRef:
        name: user-config
    resources:
      requests:
        cpu: "100m"
        memory: "130Mi"
      limits:
        cpu: "150m"
        memory: "180Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    name: user
    tier: used-for-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

