---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    container-name: web
    container-tier: frontend
spec:
  containers:
    - name: web
      imagePullPolicy: Always
      image: kiranprav/web:v2
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi"
        limits:
          cpu: "300m"
          memory: "350Mi"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: service-for-web-frontend
spec:
  type: LoadBalancer
  selector:
    container-name: web
    container-tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
